# Generated by Django 4.0.5 on 2024-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor/es')),
                ('editorial', models.CharField(max_length=50, verbose_name='Editorial')),
                ('edicion', models.CharField(max_length=50, verbose_name='Edición')),
                ('ejemplares', models.IntegerField(verbose_name='Ejemplares')),
                ('fecha_publicacion', models.DateField(max_length=50, verbose_name='Fecha de publicación')),
                ('idioma', models.CharField(max_length=50, verbose_name='Idioma')),
                ('facultad', models.CharField(max_length=50, verbose_name='Facultad')),
                ('programa_academico', models.CharField(max_length=50, verbose_name='Programa académico')),
                ('anotacion', models.CharField(max_length=300, null=True, verbose_name='Anotación')),
                ('solicitante', models.CharField(choices=[('Estudiante', 'Estudiante'), ('Docente', 'Docente')], default='', max_length=50, verbose_name='Solicitante')),
                ('estado', models.CharField(choices=[('Existente', 'Existente'), ('En tramite', 'En trámite'), ('Inexistente', 'Inexistente'), ('Sin revisar', 'Sin revisar')], default='Sin revisar', max_length=50, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
