# Generated by Django 4.0.5 on 2024-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmodel',
            name='anotacion',
            field=models.CharField(blank=True, default='No aplica', max_length=300, verbose_name='Anotación'),
        ),
        migrations.AlterField(
            model_name='solicitudmodel',
            name='idioma',
            field=models.CharField(choices=[('Español', 'Español'), ('Ingles', 'Ingles')], default='', max_length=50, verbose_name='Idioma'),
        ),
    ]
