# Generated by Django 4.0.5 on 2024-04-30 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0004_alter_solicitudmodel_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmodel',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.date.today, max_length=50, verbose_name='Fecha de solicitud'),
        ),
    ]
