# Generated by Django 4.0.5 on 2024-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0005_alter_solicitudmodel_fecha_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromodel',
            name='fecha_publicacion',
            field=models.IntegerField(verbose_name='Fecha de publicación'),
        ),
    ]
