# Generated by Django 4.0.5 on 2024-04-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0008_alter_solicitudmodel_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmodel',
            name='libro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='libro', to='material_bibliografico.libromodel', verbose_name='Libro'),
        ),
    ]
