# Generated by Django 4.0.5 on 2024-05-16 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('material_bibliografico', '0013_notificacionmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionmodel',
            name='destinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinario', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='solicitudmodel',
            name='facultad',
            field=models.CharField(choices=[('1', 'Ciencias Agrarias y del Ambiente'), ('2', 'Ciencias Básicas'), ('3', 'Ciencias Empresariales'), ('4', 'Ciencias de salud'), ('5', 'Educación, Artes y Humanidades'), ('6', 'Ingeniería')], max_length=300, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='solicitudmodel',
            name='nivel_revision',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=50, verbose_name='Nivel de revisión'),
        ),
        migrations.AlterField(
            model_name='solicitudmodel',
            name='programa_academico',
            field=models.CharField(choices=[('1', 'Ingeniería Agroindustrial'), ('2', 'Ingeniería Agronómica'), ('3', 'Ingeniería Ambiental'), ('4', 'Ingeniería Biotecnológica'), ('5', 'Zootecnia'), ('6', 'Química Industrial'), ('7', 'Administración de Empresas'), ('8', 'Contaduría Pública'), ('9', 'Comercio Internacional'), ('10', 'Enfermería'), ('11', 'Seguridad y Salud en el Trabajo'), ('12', 'Comunicación Social'), ('13', 'Trabajo Social'), ('14', 'Derecho'), ('15', 'Arquitectura'), ('16', 'Ingeniería Civil'), ('17', 'Ingeniería de Sistemas'), ('18', 'Ingeniería Electrónica'), ('19', 'Ingeniería Electromecánica'), ('20', 'Ingeniería Industrial'), ('21', 'Ingeniería de Minas'), ('22', 'Ingeniería Mecánica')], max_length=300, verbose_name='Programa académico'),
        ),
    ]
