# Generated by Django 4.0.5 on 2024-06-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0014_alter_notificacionmodel_destinario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmodel',
            name='nivel_revision',
            field=models.CharField(choices=[('1', 'Creada y enviada'), ('2', 'Solicitud enviada a decano'), ('3', 'Solicitud enviada a biblioteca'), ('4', 'Solicitud enviada a vicerrector'), ('5', 'Aprobada'), ('6', 'Rechazada')], default='1', max_length=50, verbose_name='Nivel de revisión'),
        ),
    ]
