# Generated by Django 4.0.5 on 2024-06-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0015_alter_solicitudmodel_nivel_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacionmodel',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='publicacionmodel',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
    ]
