# Generated by Django 4.0.5 on 2024-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0016_alter_publicacionmodel_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionmodel',
            name='facultad',
            field=models.CharField(choices=[('1', 'Ciencias Agrarias y del Ambiente'), ('2', 'Ciencias Básicas'), ('3', 'Ciencias Empresariales'), ('4', 'Ciencias de salud'), ('5', 'Educación, Artes y Humanidades'), ('6', 'Ingeniería')], max_length=300, null=True, verbose_name='Facultad'),
        ),
        migrations.AlterField(
            model_name='notificacionmodel',
            name='destinario',
            field=models.CharField(choices=[('Decano', 'Decano'), ('Biblioteca', 'Biblioteca')], max_length=50, verbose_name='Destinatario'),
        ),
    ]
