# Generated by Django 4.0.5 on 2024-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0017_notificacionmodel_facultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmodel',
            name='email_solicitante',
            field=models.EmailField(default='', max_length=254, verbose_name='Email solicitante'),
        ),
    ]
