# Generated by Django 4.0.5 on 2024-06-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0018_solicitudmodel_email_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libromodel',
            name='autor',
            field=models.CharField(max_length=150, verbose_name='Autor/es'),
        ),
        migrations.AlterField(
            model_name='libromodel',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
