# Generated by Django 4.0.5 on 2024-06-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0019_alter_libromodel_autor_alter_libromodel_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasLimiteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio de solicitudes')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin de solicitudes')),
            ],
            options={
                'verbose_name': 'Fecha limite',
                'verbose_name_plural': 'Fechas limmite',
            },
        ),
    ]
