# Generated by Django 4.0.5 on 2024-06-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0020_fechaslimitemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropuestasExcelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Propuesta excel',
                'verbose_name_plural': 'Propuestas excel',
            },
        ),
    ]
