# Generated by Django 4.0.5 on 2024-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0021_propuestasexcelmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestasexcelmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='propuestasexcelmodel',
            name='titulo',
            field=models.TextField(default='', verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='propuestasexcelmodel',
            name='url',
            field=models.TextField(default='', max_length=500, verbose_name='Url'),
        ),
    ]
