# Generated by Django 4.0.5 on 2024-06-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_bibliografico', '0022_remove_propuestasexcelmodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestasexcelmodel',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
