# Generated by Django 4.0.5 on 2024-04-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userinformationmodel_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationmodel',
            name='identification',
            field=models.CharField(help_text='Ingresa número de identificación', max_length=30, unique=True, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='userinformationmodel',
            name='user_type',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Director plan de estudios'), ('3', 'Director de departamento'), ('4', 'Decano'), ('5', 'Biblioteca'), ('6', 'Vicerrector')], help_text='Seleccione un tipo de usuario', max_length=255, verbose_name='Tipo de usuario'),
        ),
    ]
