# Generated by Django 4.0.5 on 2024-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userinformationmodel_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformationmodel',
            name='user_facultad',
            field=models.CharField(blank=True, choices=[('1', 'Administrador'), ('2', 'Director plan de estudios'), ('3', 'Director de departamento'), ('4', 'Decano'), ('5', 'Biblioteca'), ('6', 'Vicerrector')], help_text='Seleccione una facultad', max_length=255, null=True, verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='userinformationmodel',
            name='user_programa',
            field=models.CharField(blank=True, choices=[('1', 'Administrador'), ('2', 'Director plan de estudios'), ('3', 'Director de departamento'), ('4', 'Decano'), ('5', 'Biblioteca'), ('6', 'Vicerrector')], help_text='Seleccione un programa academico', max_length=255, null=True, verbose_name='Programa academico'),
        ),
    ]
